/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-south-1",
  aws_cognito_region: "ap-south-1",
  aws_user_pools_id: "ap-south-1_A6pe3GZ8s",
  aws_user_pools_web_client_id: "oip041imotsorip0u4drv6rhi",
  aws_cloud_logic: "enable",
  aws_cloud_logic_custom: [
    {
      name: "asetuapipoc",
      endpoint: "https://suk3v9yzr4.execute-api.ap-south-1.amazonaws.com/prod/",
      region: "ap-south-1",
    },
  ],
};

export default awsmobile;
